apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - es-ai/ks.yaml
  - es-carottage/ks.yaml
  - es-homeassistant/ks.yaml
  - es-ollama/ks.yaml  
  - es-proxmox/ks.yaml 
  - es-prusa/ks.yaml  
  - namespace.yaml