apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aSkgd2D3M0A1zQx/YzEhXNZSkt+d2/2rqUsJyb/cboF6tKLNXqJ6PQ4TEwxkl/oVhcbG29Vxgs9h8PvUdn5H4Z/wc98HtcbCMVzm5koGu0U9AEjRYxXEtDJ/aulOuKDFZ6bnC4lXPmQnaVehWF62DE0EGFgIAjodQoWe2t1ockw/PRyHMS02aRotgkcrD9LKdD2tTNQjcU1tzu1hty88FMXBr3jd7ZgHa2YapDzVrl19ABvh6HJL0n5VrWT6yNTF/aKQZYS5dzVsjsp+S6RbVcCVRnalsVmLaqZhxbOT95XlYTBvK4uoGGcPcMuE7Ts9FHvT8qp3QffdYT7IQhl/5lFTASr8XvHiX0ZlIadoPTZbyVU/8ffxgnaAo0hiOlqv,iv:ZKyYGysHpDIMtSpOKFLxTZ7O3ZbrxqzmtmVT/BKx1cM=,tag:6RmZaM3qsjglX3vx23fCTA==,type:str]
    identity.pub: ENC[AES256_GCM,data:SS3Kbqixsr7Ceit80p9yOoo6P7FpzTBPb2WqBMDK3JTx3/FAbgfJahVb9bjNB/CZGzzKPTxLvZtopk0Tnyn/sLXadU0d+cm9VbKLkx+5ST08kKkNxeytCLm6FKSO3a6oHgOHksD8EA02i7Z1NNSlW9o9qoVFFQaToBv4fHYiHUgzpKZ1voRcbIZQuiQgIUQH29iSQKU7ngExFSfBqqrWluddnT7RWp7q2VGozIHIguJWNwOB5FB+VhcjwJBLDym0CKbABY/L04YgQGBA1g==,iv:KnZxDMpnDjwgHvrhF49bz5EogURD/N850dI96wnuwrI=,tag:sE/cUFI06YkbWA+u6CD4Hw==,type:str]
    known_hosts: ENC[AES256_GCM,data:hR/q56+WdQBo2+WO2UBOZwPvgSVzwVjRMzEX+IPjb5iGHGKH0AwOaoTy4XHr3x6nPmWugDVOmiE/dMQFM6F9FfA4U9TlLI+amVSozFOqExZpCoDeJQddub7FzXeaP30iuLa5vVQBJQQQ36fboV6TzAVn3v3zuPZeY3Ut+1J6eCFUcx6OR2KJ5KD5DIDqAiz5n+iQcqQvpThVt+y+O2JVUz/fXVxG1QWpr7kR,iv:rBoxZfmTQgCwmOjmGhhCfvXR5A45bc+g8a+9SgTE380=,tag:TyNotcZ+fVfUWnN1uJhhYA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0M0p2MkFodTFoK2VFVi9K
            ZUN4SkFzY0FLZ2dVb1BOK2x0dWpMdXRQb3h3CmdXQm0xWWNTY3c0RnRWUUduZzFa
            QTlFa0V6UHo2WjI3alJpKzdnUDRDVEEKLS0tIEdERXhuUEdZNnE5SzUxcER1WUNx
            NUlIdWd2cUx6MHZqWlRRdHB5MnNVaUEKIr5jZPYWuKaWcdscF3aeYDKmTbmYHJRN
            nUd+DABTDIytXNQZEVMZLZRMuiDmOSqWEzRSpBfHzCBCVlcMmYhmDQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-21T13:06:16Z"
    mac: ENC[AES256_GCM,data:pKGnBGmZkf2leRTJtRt+FWStRBCYvdHTY/hRaMZ/Uv6nFsKQQggu9hUU/p2NuFRoO5q7W1Lpz55sHS0k/c7M3mX7MTc/CooPlN+EdK2iI/t0c+hU4gH7Fl5+Ciyq56Sg6jEgJBvvfEX8o0rYKgwuEgbJYluX0nzpRoVp99FslSk=,iv:Utnyk7LcH43I+qTmJFIiANRhvKDonnj2UppXlFnuuJg=,tag:1J/T779YmZ+Z8RiZ7ZsfGg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
