apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:kKwGObyg5DMEgL4YWIYA5QijiE9yPX01uXREa/kDcg1aPYwDEqtXUo4s4kqDTHJYn9VupFqDwTby9hBAYPYKCWU4y0KfKqp8amv0jX1s3Sr4GTEvZDnjX+l5duJ8HKQpFtn7q/d8nFDFR3Qn0rRd/6nO4yU7hOh1ykjnjHhFdQ2VjpaeIhJ1ma+6QLxmCGMr7K4s4Ywf2oOa6KAPHRT67cHa/lO13Qva11ZsFSfokUUXHef47kVH36wzVrDJSbClf1DPfyaAGp4zDVLqPDs4pvGU5gdoZtYpprCqDIFsxaoEBBIrJUmXdjJZeOeFY9OC3gctydL3WtYWlVfKTzpFiDyNUGT34fzqISgRwQ3KgE2ZdamsK51TW0FzrclF3V05,iv:/yn5mSTlxYbCzlV2Q0MUc8iqbeTS1kUhZin1/cmZk6U=,tag:ho0woCI6fY0oIG9wuuDyAw==,type:str]
    identity.pub: ENC[AES256_GCM,data:gKidIk5thuDEazTow+/7pSukZn/vbfZUV+vvTrfbJpu3Js4ISI+U9eAusKqOexxl/CUC/+odaxZFYGDregusy0QqScNhsnWmBTzSh7WJcCAXCwNbqLJXLCJmuw0vnv4P+WzeXhDy+dXloKpHLC7jEB3w2c9WAXoCRz4Etgd8B+uropB0SJtfqV7biadK0BiBASwwhTY0ovl+/VEPYx8/DFdgqVN7wUJEs3bOtJIUxWEb25rXSZHI1w+mURAuox8r4F5P5xZTQpUBazRqkQ==,iv:6yMmxxXJ1VEKMa2Bmu60FJxBoEAakbZ/1rWNAVrwLoo=,tag:b+5lX5ARuQngirFPUjEo4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:5wUro4HWtPYrsBV3AA2c55402AlpARVDYglMBspyGxr7Xpzh162uGkXUVagf3B9WmelVuJ/QRcgoZzpvNzcSEi2PIldHXjlyovBdLgLZm20yPqCVJxudTK30rsd0CgJUfkHgGGC+LZ8JB0iApkOW94jJtVXU0vF2utvW3dfbew4vHKeLbZjfigSfvuew1F8zyTIqI/0GQWMWfdj4No+wKEWf3YCPVrGRayOF,iv:vvlgb97PgnAPQ9umePZOwy3+mTk4h30ASFEDv+vlkOU=,tag:GTDmM+utU0x+oftu6gXX3A==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VVY5MGNqOGg5SHltUUdY
            WGNzbHVzZTJ3b0hRL2lZRjM3Z29oNDN1cUdnClN4RnMyRmdSaWRJU3JzQzRNOTY1
            ditDRDVsVFVUOW8wc2JRWExhVVh1ZE0KLS0tIEZvL1dQejFoWW1JZjZvODhoZE5r
            a3N6UmVuTFVBSEtkeEFJczZjMG1SVEkKAmDKfjZP52OfRa7iTuXWAT/7t80m1kqb
            HvuFbICv1wz8MBzYVIhuRCWfHTL6E3Y3S2339myxHMnwUxmZZQXXmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-08-17T12:31:42Z"
    mac: ENC[AES256_GCM,data:8c4BkH54w7JYJtqibWHvL8TP3ljHHsBFtKcMQmE8V+YVD7bGwfTGrsQwoeNiyb+2TZileh3uhYUN1UwycU3XqYbbD0tRYUTFseGoUHL/6GxxkamAO+01KOT/RFh0E2Bsk17Yu7oG04IE0YBTRL4bsDzUmG4mzmDebQY6i0xHBms=,iv:AAtAjKmhq6T3lmuSxp8L95aTPxMGNObQebvtzHvvKzY=,tag:5jDv8EMhvrtlkiCO63bDYg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
