apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:iw5QoZt1sveh7FxhiFGtg2BKMyRum1axKsUkQ2efz2z9No8Cr4kSzpoyF84wlAx2OIOLxF2V77INnBiUwal+uKXd0Jp6Qu91swz1c11Nz6HZhaI/klh7kheVVuZh5WHC6yGR54P6jQ1cnpEjAHpEnSsz6rO1O8XmbFy9iRYQeuj0zsEj6xeqnaLs5M9+sWIZOVecTo2LPTHlqG/e5J72lqeSBwTIuS5t1VhXaqXe//nslqZbX7yAL0wv5hvBC/W+eTYpNi/4JK1n/2EPU3ROM38E1QVvn7m5zisHqWijp+X4vxE1Xl//PNZ9N32Cf1XuSlb84ktrIpU8McJljHR7zM+A+MGAG+D5naVP3f1rk7Sm+K6xc8wwQYhFMLPHcCZN,iv:hwzVJ4DDZZkwh/RR3mVJEEqBz8Ba3qOuwU763hc95AM=,tag:4lc9INsmQltdlR1uq9ldYg==,type:str]
    identity.pub: ENC[AES256_GCM,data:Mv53YnEBd0k4E6B+dfJMZEeYG3AyJgtUn3tMd5iRJj3XhyCvngDbPXCVzaXtsHcjyRjbITwHoHZl7OEUe9kuiyOvI1H9N98N9WWlgOP4fN49EB7i9hr9Os7d1T7uky13KQq13fLAIttAV3G8/tJbX5CCrZlU5cl23QGgXjv+U8te1KAG4m4n5I/fIbaAAlBkIpVN+XzaD02INo62rW/dl9f+TnAS21fuwyeh6lFoUKdkPLSkCJoDY1ok2j6ef6yhXDNWrA3bS1JQbgWt7A==,iv:deWcDYSANluudwwyip1+8A9AuZOd/BjJglr3ExhXTxU=,tag:uSa+LOSPXV+caZ88mnYmIA==,type:str]
    known_hosts: ENC[AES256_GCM,data:9NrzLcq8K8zAHSTWSeS9j2Ga53EiQx3RS9CwSqiBo4oVhaIyEBqWNOXifgud3Mre2ZNoECM1u4K9fLpO1DKwGIQdunE25Jf04afkNNtg40LZUVpJ74V2SLQcezHraaYhXh6XhaUV1x1clzwq4Dphe6mnG64zpm5QfcSXMXj6YFlEaUNc7auoUZvXYqFBeW72JFjEGzJQ2DEPeDGA9AMLsw0xK0Zo84YDZwx7,iv:L2h6VPoZu9my9pVu6ON8u+i/MIqRfPCN+mRsHWAbjw4=,tag:6qa7m9KU6zw4xQoSzy+gcA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MTFMZmMyazJJdkZidXBu
            NEFHc2t4MjRiN3RMcmJlOU1KMmlJb2liUWlFClM1TFY0cTMwYnJmU0lJcWh5eTc5
            aXJjSE1DYXZJQmR1cXVQemRRS3p2WkUKLS0tIDhyL2p1OFp3VmVyWkdUeEVucXdq
            RVpZaVZsNVN1VHprK0pUYnBYQWg3OWsKL4dykF+do6PSVgwsb1p02JUqZm6Elrcv
            IXkCBSes05KiE0UfYoVttOvQkw7tthc/WfSbR/P5sTndlnlF6BkxvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cjnkxd7efyuzdg9z852v7sa6y9jlv99cxnzdu70c4yu3qg58p93qs7svgs
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-07-15T07:40:10Z"
    mac: ENC[AES256_GCM,data:zZgcLbggR7AtIeLGdEpEG3pyAGa8fq20DoBU+7p/TRZvsY63kDtfIPIdPYVuyYk/qf8n7QDh0a31BCJWQYclh686nXbXC1DPz73GDDnq0lkvhZ7GO9KQ7AWC9MwQHyZ1XPfUWw85VVxVvKQQJwzFXuOjEuqI9ajVLi+kLfFg1jA=,iv:D0Q0RtXP3p7pEw1wa+em7ZfsHzBv9JiXOmIKYzBhtC8=,tag:AZVniQhp2y2+4sPN2D+BZw==,type:str]
    shamir_threshold: 3
    version: 3.13.1
