---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 9.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "${S3_BUCKET}"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}"

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: lldap.${DOMAIN_0}
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
    
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LLDAP_HTTP_URL: https://lldap.${DOMAIN_1}
                LLDAP_LDAP_BASE_DN: dc=${DN},dc=${DC}
                LLDAP_LDAP_USER_DN: admin
                LLDAP_LDAP_USER_EMAIL: ${LLDAP_USER_EMAIL}
                LLDAP_LDAP_USER_PASS: ${LLDAP_PASSWORD}
                LLDAP_SMTP_OPTIONS__FROM: "LLDAP <${SMTP_USER}>"
                LLDAP_SMTP_OPTIONS__PASSWORD: "${SMTP_PASSWORD}"
                LLDAP_SMTP_OPTIONS__PORT: ${SMTP_PORT}
                LLDAP_SMTP_OPTIONS__REPLY_TO: "Do not reply <${SMTP_USER}>"
                LLDAP_SMTP_OPTIONS__SERVER: ${SMTP_HOST}
                LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION: TLS
                LLDAP_SMTP_OPTIONS__USER: ${SMTP_USER}
                LLDAP_VERBOSE: false
                LLDAP_key_file: /data/private_key
    
    cnpg:
      main:
        cluster:
          singleNode: true
        mode: standalone #recovery pour restore
        backups:
          enabled: true
          credentials: minio
          retentionPolicy: "14d"
          revision: "3"
        recovery:
          enabled: false
        monitoring:
          enablePodMonitor: true

    persistence:
      data:
        enabled: true
        volsync:
          - name: data
            type: restic
            credentials: minio
            src:
              enabled: true
            dest:
              enabled: false
