name: Test GitHub Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Bonjour
        run: |
          echo "================================"
          echo "GitHub Actions fonctionne !"
          echo "================================"

      - name: Version Python
        run: python3 --version

      - name: Afficher les fichiers
        run: ls -la