apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 22.13.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m  
  timeout: 20m
  maxHistory: 3 
  driftDetection:
    mode: warn   
  install:
    createNamespace: true

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  
  values:
    global:
      stopAll: false
    credentials:
      minio:
        type: s3
        url: "${S3_URL}"
        bucket: "taloscluster"
        accessKey: "${S3_ACCESKEY}"
        secretKey: "${S3_SECRETKEY}"
        encrKey: "${S3_ENCRKEY}" 
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: prowlarr.${DOMAIN_0}
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_0}"  
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            name: "prowlarr"
            description: "prowlarr"
            group: "Media"
            weight: 3
            widget:
              enabled: false
    persistence:
      config:
        volsync:
        - name: config
          type: restic
          credentials: minio
          dest:
            enabled: true
          src:
            enabled: true
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PROWLARR__AUTH__METHOD: External